### ISSUE TITLE
Frontend: Website Navigation

### ISSUE THREAD

**Issue by noah1837** [nicolasbreuni/Tinf18C_Team_2_Profinet_DCP_Client#5]
User should be able to navigate on the Website ( Left Side Bar)

**Comment by noah1837** [comment]
Done @nicolasbreuni

**Comment by noah1837** [comment]
Can you cache previous opened register cards of devices?

**Comment by nicolasbreuni** [comment]
Not necessary, because the browser can deliver this functionality by http caching (correct headers needed).
